##配置基础配置文件
#
server:
  port: 8090

spring:
  application:
    name: app-user
  datasource:
    url: jdbc:mysql://localhost:3306/zigar_cloud_user?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: cu_admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 1
  zipkin:
    base-url: http://localhost:9000/
  #    sender:
  #      type: rabbit
  sleuth:
    sampler:
      probability: 1.0   #2.0后percentage改为probability
  rabbitmq: #RabbitMQ相关的配置
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径

###SpringCloud
#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://zigar:123456@eureka1:7100/eureka/,http://zigar:123456@eureka2:8100/eureka/,http://zigar:123456@eureka3:9100/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    instance-id: ${spring.application.name}###${server.port} #指定实例id

#开启所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
