#自定义配置
zigar:
  hostname: 192.168.109.10
  eureka:
    username: zigar
    password: 123456

#系统配置

spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysql://${zigar.hostname}:3306/zigar_cloud_user?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: zigar_user_admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 1
  zipkin:
    base-url: http://${zigar.hostname}:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0   #2.0后percentage改为probability
  rabbitmq: #RabbitMQ相关的配置
    host: ${zigar.hostname}
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径

#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://${zigar.eureka.username}:${zigar.eureka.password}@${zigar.hostname}:7100/eureka/, http://${zigar.eureka.username}:${zigar.eureka.password}@${zigar.hostname}:8100/eureka/, http://${zigar.eureka.username}:${zigar.eureka.password}@${zigar.hostname}:9100/eureka/

# 在feign中开启熔断器
feign:
  hystrix:
    enabled: true

#开启所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"