#自定义配置
zigar:
  hostname: 192.168.109.10
  eureka:
    username: zigar
    password: 123456

spring:
  application:
    name: server-zuul #指定服务名
  zipkin:
    base-url: http://${zigar.hosename}:9411/
  sleuth:
    sampler:
      probability: 1.0   #2.0后percentage改为probability
#  rabbitmq: #RabbitMQ相关的配置
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone: http://${zigar.eureka.username}:${zigar.eureka.password}@${zigar.hostname}:7100/eureka/, http://${zigar.eureka.username}:${zigar.eureka.password}@${zigar.hostname}:8100/eureka/, http://${zigar.eureka.username}:${zigar.eureka.password}@${zigar.hostname}:9100/eureka/

#开启所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

###服务网关
zuul:
  routes: #定义服务转发规则
    file-service: #file-service这个名字任意取的
      serviceId: servie-file
      path: /file-service/** #配置请求URL的请求规则
    user-service: #user-service这个名字任意取的
      serviceId: service-user
      path: /user-service/** #配置请求URL的请求规则

