##配置文件都在github上，只保留application-name即可
##配置基础配置文件
#
server:
  port: 8010
#
spring:
  application:
    name: service-file
  datasource:
    url: @mvn.service-file.db.url@
    username: @mvn.service-file.db.username@
    password: @mvn.service-file.db.password@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 1
  zipkin:
    base-url: @mvn.zinpkin.url@
    sender:
      type:
  sleuth:
    sampler:
      probability: 1.0   #2.0后percentage改为probability
  rabbitmq: #RabbitMQ相关的配置
    host: @mvn.rabbitmq.hostname@
    port: @mvn.rabbitmq.port@
    username: @mvn.rabbitmq.username@
    password: @mvn.rabbitmq.password@

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径

###SpringCloud
#服务注册到eureka注册中心的地址
eureka:
  client:
    service-url:
      defaultZone:  @mvn.eureka.client.serviceUrl.defaultZone@

# 在feign中开启熔断器
feign:
  hystrix:
    enabled: true

#开启所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"

